### ISSUE TITLE
Unexpect error in runtime, AssertionError: DatabaseBackend is not running

### ISSUE THREAD

**Issue by Lynskylate** [encode/databases#96]
I'm developing a web app with starlette and database, and use docker-compose to run it, but I met an unexpected problem.

My docker-compose file is below
```yaml
version: "3.0"

services:
  app:
    build: ./
    links:
      - "db:mysqlserver"
    volumes:
      - ./db/envfile:/app/.env
    ports:
      - 8000:8000
  db:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always
    hostname: mysqlserver
```
The database wasn't avaliable when app start, so i add a execption handle for it.
```python
async def connect_db():
    try:
        await database.connect()
    except Exception as e:
        logger.error("connect db error, res is  {}".format(e))
        await asyncio.sleep(3)
        asyncio.ensure_future(connect_db())

app.add_event_handler("startup", connect_db)
```
But database.connectdidn't raise any exception, so i can't handle it.
I don't know if the error handling is correct, maybe should throw exception when connect?
Thank you
